# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dasiBom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dasiBom
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod ‘Firebase/Database’

  # pod 'SnapKit', '~> 5.0.0'

end
