# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dasiBom_for_dementiaPrevention' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn', '< 5.0.0'

  # Pods for dasiBom_for_dementiaPrevention

end
